server.port: 7003
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db

---
spring.config.activate.on-profile: create-ddl-script

spring.jpa.properties.jakarta.persistence.schema-generation:
  create-source: metadata
  scripts:
    action: create
    create-target: crac/sql-scripts/create-tables.sql

---
spring.config.activate.on-profile: crac

# CRaC support, see https://github.com/spring-projects/spring-lifecycle-smoke-tests/blob/main/data/data-jpa/README.adoc
# Lifecycle configuration guidance
# Specify explicitly the dialect (here for MySQL, adapt for your database)
spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect

# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

# Database initialization will typically be performed outside of Spring lifecycle
spring.jpa.hibernate.ddl-auto: none
spring.sql.init.mode: never

# In order to allow checkpoint/restore to work as expected, Hikari pool suspension should be enabled.
spring.datasource.hikari.allow-pool-suspension: true
