# syntax=docker/dockerfile:1.3-labs
# The above syntax directive is required to get support for "RUN --security=insecure"

# Does not work starting with azul/zulu-openjdk:21.0.4-21.36-jdk-crac, error message:
# - Error (criu/cr-restore.c:1518): Can't fork for 7: Read-only file system
# - Error (criu/cr-restore.c:2605): Restoring FAILED.
# - Error (criu/cr-restore.c:1835): Pid 13 do not match expected 7
# FROM azul/zulu-openjdk:21-jdk-crac

FROM azul/zulu-openjdk:21.0.3-21.34-jdk-crac

ADD build/libs/*.jar app.jar

# The docker and crac profiles are both required. However, the crac profile is only required for the review service.
RUN --security=insecure SPRING_PROFILES_ACTIVE=docker,crac java -Dspring.context.checkpoint=onRefresh -XX:CRaCCheckpointTo=checkpoint -jar app.jar || if [ $? -eq 137 ]; then return 0; else return 1; fi

EXPOSE 8080
ENTRYPOINT ["java", "-XX:CRaCRestoreFrom=checkpoint"]
